#   FLASK SETTINGS
FLASK_DEBUG = True
Error_404_HELP = False

#   FLASK-RESTPLUS SETTINGS
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False

#   APPLICATION SETTINGS
MINE_TOLERANCE = 5
